/**
 * build-image-map.ts
 *
 * Reads images from public/product-images/, resizes to 96x96 JPEG thumbnails,
 * and generates src/pwa/data/productImageMap.ts with base64 data URLs.
 *
 * Usage: npx ts-node scripts/build-image-map.ts
 *   (or: npx tsx scripts/build-image-map.ts)
 *
 * Requires: npm install -D sharp (if not already installed)
 */

import { readdirSync, writeFileSync } from 'fs'
import { join, basename, extname, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

async function main() {
  // Dynamic import so the script fails gracefully if sharp isn't installed
  let sharp: typeof import('sharp')
  try {
    sharp = (await import('sharp')).default as unknown as typeof import('sharp')
  } catch {
    console.error('Error: "sharp" is required. Install it with: npm install -D sharp')
    process.exit(1)
  }

  const imagesDir = join(__dirname, '..', 'public', 'product-images')
  const outFile = join(__dirname, '..', 'src', 'pwa', 'data', 'productImageMap.ts')

  const files = readdirSync(imagesDir).filter((f) => /\.(jpe?g|png|webp)$/i.test(f))

  if (files.length === 0) {
    console.log('No images found in public/product-images/ — generating empty map.')
  }

  const entries: Record<string, string> = {}

  for (const file of files) {
    const itemNumber = basename(file, extname(file))
    const filePath = join(imagesDir, file)

    const buffer = await sharp(filePath)
      .resize(96, 96, { fit: 'cover' })
      .jpeg({ quality: 70 })
      .toBuffer()

    const base64 = `data:image/jpeg;base64,${buffer.toString('base64')}`
    entries[itemNumber] = base64
    console.log(`  ✓ ${file} → ${(buffer.length / 1024).toFixed(1)}KB`)
  }

  const lines = Object.entries(entries)
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
    .map(([key, val]) => `  "${key}": "${val}",`)
    .join('\n')

  const output = `// Auto-generated by scripts/build-image-map.ts — do not edit manually
// Run: npx tsx scripts/build-image-map.ts
export const PRODUCT_IMAGE_MAP: Record<string, string> = {
${lines}
}
`

  writeFileSync(outFile, output, 'utf-8')
  console.log(`\nGenerated ${outFile} with ${Object.keys(entries).length} images.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
